### ISSUE TITLE
Feat : 로그인 API 구현 

### ISSUE THREAD

**Issue by moonyaeyoon** [SMUING-D/BE-UMC-SMU#4]
## Description
로그인 API 구현 : jwt 토큰 사용 , 학번과 비밀 번호 이용해서 로그인 

## To-do
- [ ] 필수 정보 누락 체크 : 학번, 비밀 번호 
- [ ] 사용자 확인 : 입력 정보에 해당하는 사용자 존재 여부 확인 
- [ ] JWT 토큰 생성 : 로그인 시 JWT 토큰 생성 

## ETC
기타 참고사항을 적어주세요.
