### ISSUE TITLE
[Feat] 마이페이지 API

### ISSUE THREAD

**Issue by moonyaeyoon** [SMUING-D/BE-UMC-SMU#53]
## Description
마이페이지 화면에 필요한 API 구현

## To-do
- [ ] UserDB에 Description 추가 
- [ ] UserDB에 성별 값 변경
- [ ] 이름, 닉네임, 소개 수정 API 

## ETC
기타 참고사항을 적어주세요.
